apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: kube-system
  annotations:
    # If using IRSA, attach the IAM role ARN here via eks.amazonaws.com/role-arn
    # eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/fluetbit-k8s-role
